all:
    # install detail package locally
	python3 setup.py build_ext --inplace
	rm -rf build

install:
    # install detail package to the Python site-packages
	python3 setup.py build_ext install
	rm -rf build
